/* Plugin System Central Include File
 *
 * This file includes all plugin header files. Plugins are automatically
 * discovered by the build system and their headers are included here.
 *
 * Each plugin should register itself in its implementation file.
 *
 * Copyright (c) 2025 the_louie
 *
 * This example code is in the Public Domain (or CC0 licensed, at your option.)
 *
 * Unless required by applicable law or agreed to in writing, this
 * software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied.
 */

#ifndef __PLUGINS_H__
#define __PLUGINS_H__

/* This file will be automatically generated by CMake to include all
 * discovered plugin headers. For now, it's a placeholder that can be
 * manually updated or will be auto-generated during build.
 *
 * Plugin headers should be included in the format:
 *   #include "plugins/<plugin-name>/<plugin-name>_plugin.h"
 *
 * Example:
 *   #include "plugins/effects/effects_plugin.h"
 *   #include "plugins/sequence/sequence_plugin.h"
 */

/* Note: Plugin headers will be automatically included here by the build system.
 * This file serves as the central include point for all plugins.
 *
 * If no plugins are present, this file is still valid (empty includes).
 */

#endif /* __PLUGINS_H__ */
